source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Use Capistrano for deployment
group :development do
  gem "capistrano", "~> 3.11", require: false
  gem "capistrano-rails", "~> 1.4", require: false
  gem 'capistrano-passenger', '~> 0.2.0', require: false
  gem 'capistrano-rbenv', '~> 2.1', '>= 2.1.4', require: false

  # To provide support for ed25519 encrypted key
  gem 'ed25519', '>= 1.2', '< 2.0'
end
