require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - test/**/*
    - bin/*
    - script/*

  NewCops: enable

#################### Style ###############################

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: false

Style/RedundantReturn:
  Description: Don't use return where it's not required.
  Enabled: true
  AllowMultipleReturnValues: true

#################### Metrics ###############################

Metrics/MethodLength:
  Description: Avoid methods longer than 10 lines of code.
  Max: 15
